"use client";

import { FormEvent, useEffect, useState } from "react";
import { api } from "@/lib/api";

type Trend = { candidate_id: string; platform: string; title?: string; canonical_url: string; score: number; score_confidence: number; selected: boolean; source_label: string; source_limitations?: string; score_explanation: string[] };
export default function TrendExplorer() {
  const [trends, setTrends] = useState<Trend[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [platform, setPlatform] = useState("youtube"); const [url, setUrl] = useState("");
  async function load() { try { setTrends(await api<Trend[]>("/api/trends")); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load trends"); } }
  useEffect(() => { void load(); }, []);
  async function discover() { setBusy(true); try { await api("/api/workflows/trends?max_candidates=30&select_limit=10", { method: "POST" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Discovery failed"); } finally { setBusy(false); } }
  async function importUrl(e: FormEvent) { e.preventDefault(); setBusy(true); try { await api("/api/trends/import", { method: "POST", body: JSON.stringify({ platform, url, metrics: {} }) }); setUrl(""); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Import failed"); } finally { setBusy(false); } }
  return <section><div className="page-heading"><div><p className="eyebrow">Transparent opportunity scoring</p><h1>Trend Explorer</h1><p>Metrics are ranked by recency, velocity, engagement, relevance, confidence, safety, and originality opportunity. Missing metrics reduce confidence rather than being fabricated.</p></div><button className="button primary" onClick={discover} disabled={busy}>Run Trend Discovery</button></div>{error && <div className="error">{error}</div>}<form className="panel form-grid" onSubmit={importUrl}><div className="field"><label>Platform</label><select value={platform} onChange={(e) => setPlatform(e.target.value)}><option value="youtube">YouTube</option><option value="tiktok">TikTok</option><option value="instagram">Instagram</option></select></div><div className="field"><label>Manual video URL</label><input required value={url} onChange={(e) => setUrl(e.target.value)} placeholder="Paste a user-supplied public URL" /></div><div className="field full"><button className="button" type="submit">Import Reference</button></div></form><div className="panel table-wrap" style={{ marginTop: 16 }}><table><thead><tr><th>Rank</th><th>Platform</th><th>Trend</th><th>Score</th><th>Source and limits</th></tr></thead><tbody>{trends.map((trend, index) => <tr key={trend.candidate_id}><td>{index + 1}{trend.selected ? " ✓" : ""}</td><td>{trend.platform}</td><td><a href={trend.canonical_url} target="_blank" rel="noreferrer">{trend.title ?? trend.candidate_id}</a><p className="muted">{trend.score_explanation.join(" ")}</p></td><td>{trend.score.toFixed(1)}<br/><span className="muted">{Math.round(trend.score_confidence * 100)}% confidence</span></td><td>{trend.source_label}<p className="muted">{trend.source_limitations}</p></td></tr>)}</tbody></table></div></section>;
}
