"use client";

import { FormEvent, useEffect, useState } from "react";
import { api } from "@/lib/api";

const initial = { name: "My Brand", niche: "General education", target_audience: "Curious adults", brand_voice: "Clear, credible, energetic", countries: ["US"], languages: ["en"], topics_include: [] as string[], topics_exclude: [] as string[], preferred_duration_seconds: 30, preferred_voice: "neutral", approved: false };
export default function BrandProfile() {
  const [form, setForm] = useState(initial); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { api<typeof initial>("/api/brand-profile").then((data) => { if (data.name) setForm({ ...initial, ...data }); }).catch(() => undefined); }, []);
  async function submit(e: FormEvent) { e.preventDefault(); try { await api("/api/brand-profile", { method: "PUT", body: JSON.stringify(form) }); setMessage("Brand profile saved."); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save"); } }
  return <section><div className="page-heading"><div><p className="eyebrow">Generation guardrail</p><h1>Brand Profile</h1><p>The content engine uses this approved profile for audience relevance, voice, exclusions, duration, and platform adaptation.</p></div></div>{message && <div className="notice">{message}</div>}{error && <div className="error">{error}</div>}<form className="panel form-grid" onSubmit={submit}><div className="field"><label>Brand name</label><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div><div className="field"><label>Niche</label><input value={form.niche} onChange={(e) => setForm({ ...form, niche: e.target.value })} /></div><div className="field full"><label>Target audience</label><textarea value={form.target_audience} onChange={(e) => setForm({ ...form, target_audience: e.target.value })} /></div><div className="field full"><label>Brand voice</label><textarea value={form.brand_voice} onChange={(e) => setForm({ ...form, brand_voice: e.target.value })} /></div><div className="field"><label>Countries, comma separated</label><input value={form.countries.join(", ")} onChange={(e) => setForm({ ...form, countries: e.target.value.split(",").map((v) => v.trim()).filter(Boolean) })} /></div><div className="field"><label>Languages, comma separated</label><input value={form.languages.join(", ")} onChange={(e) => setForm({ ...form, languages: e.target.value.split(",").map((v) => v.trim()).filter(Boolean) })} /></div><div className="field"><label>Preferred duration, seconds</label><input type="number" min="10" max="1200" value={form.preferred_duration_seconds} onChange={(e) => setForm({ ...form, preferred_duration_seconds: Number(e.target.value) })} /></div><div className="field"><label>Preferred voice</label><input value={form.preferred_voice} onChange={(e) => setForm({ ...form, preferred_voice: e.target.value })} /></div><div className="field full"><label><input type="checkbox" checked={form.approved} onChange={(e) => setForm({ ...form, approved: e.target.checked })} /> I approve this profile for generation</label></div><div className="field full"><button className="button primary" type="submit">Save Brand Profile</button></div></form></section>;
}
